Numpy operations

In [2]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing:", arr[2:7])
print("basic slicing with step:", arr[2:7:2])
print("negative indexing:", arr[-2])

basic slicing: [3 4 5 6 7]
basic slicing with step: [3 5 7]
negative indexing: 8


In [18]:
arr_2d= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print("Specific element", arr_2d[0,1])
print("Entire row", arr_2d[0])
print("Entire column", arr_2d[:,2])

Specific element 2
Entire row [1 2 3]
Entire column [3 6 9]


Sorting

In [22]:
unsorted = np.array([3,1,4,6,6,7,9,4,2])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by column", np.sort(arr_2d_unsorted, axis=0))


Sorted array [1 2 3 4 4 6 6 7 9]
Sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


Filtering

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers % 2 == 0]
print("Even numbers", even)

Even numbers [ 2  4  6  8 10]


Filter with mask

In [ ]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


Fancy indexing VS NP.where()

In [31]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where :", numbers[where_result])

[1 3 5]
NP where : [ 6  7  8  9 10]


In [38]:
condition_array = np.where(numbers % 2 == 0 , numbers*2, numbers-1)
print(condition_array)

[ 0  4  2  8  4 12  6 16  8 20]


Adding and removing Data

In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_array = np.concatenate((arr1,arr2))
print("Combined array: ", combined_array)

Combined array:  [1 2 3 4 5 6]


array compatibilty

In [44]:
a= np.array([1,2,3])
b= np.array([4,5,6,7])
c= np.array([7,8,9])

print("Compatability shape:", a.shape == b.shape)

Compatability shape: False


In [56]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row)) 
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [65]:
arr = np.array([1,2,3,4,5])
deleted =  np.delete(arr, 2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5]
