### Numpy



In [ ]:
import numpy as np


##creating array from list


In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array is:" , arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array is:" , arr_2d)

1D array is: [1 2 3 4 5]
2D array is: [[1 2 3]
 [4 5 6]]


#List vs Numpy array

In [ ]:
import time

py_list = [1,2,3]
print("Python list multiplication is: ", py_list*2)

np_array = np.array([1,2,3]) #element-wise multiplication
print("Python array multiplication is : ", np_array*2)

start = time.time()
py_list = [i* 2 for i in range(1000000)]
end = time.time()
total_time = end - start
print("pylist :",total_time)

start = time.time()
np_array = np.arange(100000) * 2
end = time.time()
total_time = end - start
print("pyarray :",total_time)

Python list multiplication is:  [1, 2, 3, 1, 2, 3]
Python array multiplication is :  [2 4 6]
pylist : 0.045027732849121094
pyarray : 0.0003924369812011719


creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("zeros array :\n",zeros)

ones = np.ones((3,3))
print("ones array :\n",ones)

full = np.full((2,2),7)
print("full array :\n",full)

random = np.random.random((2,3))
print("random array :\n",random)

seq = np.arange(0,10,2)
print("sequence array :\n",seq)

zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array :
 [[7 7]
 [7 7]]
random array :
 [[0.21521152 0.06003676 0.22409186]
 [0.83743188 0.28898766 0.2479964 ]]
sequence array :
 [0 2 4 6 8]


Vector, Matrix and Tensor


In [ ]:
vector = np.array([1,2,3])
print("Vector :",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor :", tensor)

Vector : [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Propeties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape:",arr.shape)
print("dimension :",arr.ndim)
print("size:",arr.size)
print("Dtype :",arr.dtype)

Shape: (2, 3)
dimension : 2
size: 6
Dtype : int64


Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array:",arr)

reshaped = arr.reshape(3,4)
print("\nReshaped array:",reshaped)

flattened = reshaped.flatten()
print("\nFlattened array:",flattened)

# ravel (returns view,instead of copy)
raveled = reshaped.ravel()
print("\nRaveled array:",raveled)

# Transpose
transpose = reshaped.T
print("\nTransposed array:",transpose)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
