In [2]:
import numpy as np

PROJECT1 - Students Marks Analayzer

In [6]:
###[Eng,Urdu,Math]
marks = np.array([
[78,85,90],
[65,70,60],
[88,92,95],
[50,55,58],
[90,91,89]
])

print("Average Marks Per student:", np.mean(marks,axis=1))
print("Highest Scorer Per subject:", np.max(marks,axis=0))
print("Subject-wise Average:", np.mean(marks,axis=0))
student_avg = np.average(marks,axis=1)
print("Student who passed:", np.where(student_avg>60)[0])


Average Marks Per student: [84.33333333 65.         91.66666667 54.33333333 90.        ]
Highest Scorer Per subject: [90 92 95]
Subject-wise Average: [74.2 78.6 78.4]
Student who passed: [0 1 2 4]


Project2 - Sales Data Analyzer

In [7]:
#product = day1,day2,day3,day4 
sales = np.array([
[200,300,250,400],         
[150,250,300,350],         
[400,450,500,550]         
])

#questions
print("Total Sales per day:", np.sum(sales,axis=0))
print("Total Sales per Product:", np.sum(sales,axis=1))
total_sell = np.sum(sales,axis=1)
print("Best selling product:",np.argmax(total_sell))
print("Growth per day:", np.cumsum(sales,axis=0))

#extras

print("Average sales per product:", np.mean(sales,axis=1))
total_sell = np.sum(sales,axis=0)
print("Lowest selling day:",np.argmin(total_sell))
growth = sales[:, -1] - sales[:,0]
print("Growth per product:", np.argmax(growth))

Total Sales per day: [ 750 1000 1050 1300]
Total Sales per Product: [1150 1050 1900]
Best selling product: 2
Growth per day: [[ 200  300  250  400]
 [ 350  550  550  750]
 [ 750 1000 1050 1300]]
Average sales per product: [287.5 262.5 475. ]
Lowest selling day: 0
Growth per product: 0


Project4- Random Dataset Analyzer

In [8]:

data = np.random.randint(1,100,(10,5))
print(data)

#questions

print("Mean of data-set:", np.mean(data))
print("Median of data-set:", np.median(data))
print("Standard Deviation of data-set:", np.std(data))
print("Highest value of data-set:",np.max(data))
print("Lowest value of data-set:",np.min(data))
print("All values over 70:", data > 70)
print("Sorted data:",np.sort(data))
row_avg = np.mean(data,axis=1)
print("Row avg",row_avg,"Row with Highest average is :",np.argmax(row_avg))
col_avg = np.mean(data,axis=0)
print("Column avg",col_avg,"Column with Lowest average is :", np.argmin(col_avg))
print("Total sum:", np.sum(data))


[[11 36 60 28 81]
 [ 8  5 54  8 95]
 [64 58 83 13 67]
 [51 66 83 78 91]
 [ 8 86 92  9  9]
 [77 56 98 74 22]
 [77 24  2 69 38]
 [62 16 74 93 81]
 [84 14 64 94 86]
 [90 30 98 99 87]]
Mean of data-set: 57.06
Median of data-set: 65.0
Standard Deviation of data-set: 31.827918562168026
Highest value of data-set: 99
Lowest value of data-set: 2
All values over 70: [[False False False False  True]
 [False False False False  True]
 [False False  True False False]
 [False False  True  True  True]
 [False  True  True False False]
 [ True False  True  True False]
 [ True False False False False]
 [False False  True  True  True]
 [ True False False  True  True]
 [ True False  True  True  True]]
Sorted data: [[11 28 36 60 81]
 [ 5  8  8 54 95]
 [13 58 64 67 83]
 [51 66 78 83 91]
 [ 8  9  9 86 92]
 [22 56 74 77 98]
 [ 2 24 38 69 77]
 [16 62 74 81 93]
 [14 64 84 86 94]
 [30 87 90 98 99]]
Row avg [43.2 34.  57.  73.8 40.8 65.4 42.  65.2 68.4 80.8] Row with Highest average is : 9
Column avg [53.2 39.1 70

Project5 - Recommendation System Logic

In [3]:
ratings = np.array([
[5,4,0,1],
[4,0,0,1],
[1,1,0,5],
[1,0,0,4]
])

#Questions
avg_rating = np.mean(ratings,axis=0)
print("Average Rating per movie:", avg_rating)
print("Highest Rated movie:", np.argmax(avg_rating))
print("Lowest Rated movie:", np.argmin(avg_rating))
print("Movies not watched:", np.where(ratings == 0)[0])

for i in range(len(ratings)):
         unseen = np.where(ratings[i] == 0)[0]
         print(f"User {i+1} has not watched {unseen}")

user1_unseen = np.where(ratings[1] == 0)[0]
recommended = user1_unseen[np.argmax(avg_rating[user1_unseen])]
print("The recommended movie is:",recommended)

activity = np.count_nonzero(ratings, axis=1)
print("Most active user:", np.argmax(activity))

most_viewed = np.count_nonzero(ratings, axis=0)
print("The Most Times Rated is:", np.argmax(most_viewed))

user_avg_rating = np.mean(ratings,axis=1)
print(user_avg_rating,"User with highest average rating is:", np.argmax(user_avg_rating))

popularity = avg_rating * most_viewed
print(popularity,"Most popular movie is :", np.argmax(popularity))

Average Rating per movie: [2.75 1.25 0.   2.75]
Highest Rated movie: 0
Lowest Rated movie: 2
Movies not watched: [0 1 1 2 3 3]
User 1 has not watched [2]
User 2 has not watched [1 2]
User 3 has not watched [2]
User 4 has not watched [1 2]
The recommended movie is: 1
Most active user: 0
The Most Times Rated is: 0
[2.5  1.25 1.75 1.25] User with highest average rating is: 0
[11.   2.5  0.  11. ] Most popular movie is : 0


Project-5 : Image Analaysis

In [ ]:
image = np.random.randint(0,255,(3,3))
print(image)

[[ 83 140  21]
 [ 30 118 193]
 [ 17 163 148]]


In [12]:
print(image)
print("Normalizing :", image / 255)
print("Increase Brightness:", image + 50)
print("Decrease Brightness:", image - 10)


[[ 83 140  21]
 [ 30 118 193]
 [ 17 163 148]]
Normalizing : [[0.3254902  0.54901961 0.08235294]
 [0.11764706 0.4627451  0.75686275]
 [0.06666667 0.63921569 0.58039216]]
Increase Brightness: [[133 190  71]
 [ 80 168 243]
 [ 67 213 198]]
Decrease Brightness: [[ 73 130  11]
 [ 20 108 183]
 [  7 153 138]]
