In [8]:
import numpy as np

PROJECT1 - Students Marks Analayzer

In [10]:
###[Eng,Urdu,Math]
marks = np.array([
[78,85,90],
[65,70,60],
[88,92,95],
[50,55,58],
[90,91,89]
])

print("Average Marks Per student:", np.mean(marks,axis=1))
print("Highest Scorer Per subject:", np.argmax(marks,axis=0))
print("Subject-wise Average:", np.mean(marks,axis=0))
student_avg = np.average(marks,axis=1)
print("Student who passed:", np.where(student_avg>60)[0])


Average Marks Per student: [84.33333333 65.         91.66666667 54.33333333 90.        ]
Highest Scorer Per subject: [4 2 2]
Subject-wise Average: [74.2 78.6 78.4]
Student who passed: [0 1 2 4]


Project2 - Sales Data Analyzer

In [3]:
#product = day1,day2,day3,day4 
sales = np.array([
[200,300,250,400],         
[150,250,300,350],         
[400,450,500,550]         
])

#questions
print("Total Sales per day:", np.sum(sales,axis=0))
print("Total Sales per Product:", np.sum(sales,axis=1))
total_sell = np.sum(sales,axis=1)
print("Best selling product:",np.argmax(total_sell))
print("Growth per day:", np.cumsum(sales,axis=0))

#extras

print("Average sales per product:", np.mean(sales,axis=1))
total_sell = np.sum(sales,axis=0)
print("Lowest selling day:",np.argmin(total_sell))
growth = sales[:, -1] - sales[:,0]
print("Growth per product:", np.argmax(growth))

Total Sales per day: [ 750 1000 1050 1300]
Total Sales per Product: [1150 1050 1900]
Best selling product: 2
Growth per day: [[ 200  300  250  400]
 [ 350  550  550  750]
 [ 750 1000 1050 1300]]
Average sales per product: [287.5 262.5 475. ]
Lowest selling day: 0
Growth per product: 0


Project4- Random Dataset Analyzer

In [4]:

data = np.random.randint(1,100,(10,5))
print(data)

#questions

print("Mean of data-set:", np.mean(data))
print("Median of data-set:", np.median(data))
print("Standard Deviation of data-set:", np.std(data))
print("Highest value of data-set:",np.max(data))
print("Lowest value of data-set:",np.min(data))
print("All values over 70:", data > 70)
print("Sorted data:",np.sort(data))
row_avg = np.mean(data,axis=1)
print("Row avg",row_avg,"Row with Highest average is :",np.argmax(row_avg))
col_avg = np.mean(data,axis=0)
print("Column avg",col_avg,"Column with Lowest average is :", np.argmin(col_avg))
print("Total sum:", np.sum(data))


[[12 30 63 54  5]
 [ 7 35 62 79 49]
 [42 72 42 73  8]
 [47 57 17 60 37]
 [67 34  8 71 11]
 [30 56 88 38 68]
 [54 97 51 90 60]
 [32 71 86  1 68]
 [44 95  5 74  3]
 [82 38  7 58 45]]
Mean of data-set: 47.66
Median of data-set: 50.0
Standard Deviation of data-set: 27.00711758037129
Highest value of data-set: 97
Lowest value of data-set: 1
All values over 70: [[False False False False False]
 [False False False  True False]
 [False  True False  True False]
 [False False False False False]
 [False False False  True False]
 [False False  True False False]
 [False  True False  True False]
 [False  True  True False False]
 [False  True False  True False]
 [ True False False False False]]
Sorted data: [[ 5 12 30 54 63]
 [ 7 35 49 62 79]
 [ 8 42 42 72 73]
 [17 37 47 57 60]
 [ 8 11 34 67 71]
 [30 38 56 68 88]
 [51 54 60 90 97]
 [ 1 32 68 71 86]
 [ 3  5 44 74 95]
 [ 7 38 45 58 82]]
Row avg [32.8 46.4 47.4 43.6 38.2 56.  70.4 51.6 44.2 46. ] Row with Highest average is : 6
Column avg [41.7 58.5 42.

Project5 - Recommendation System Logic

In [5]:
ratings = np.array([
[5,4,0,1],
[4,0,0,1],
[1,1,0,5],
[1,0,0,4]
])

#Questions
avg_rating = np.mean(ratings,axis=0)
print("Average Rating per movie:", avg_rating)
print("Highest Rated movie:", np.argmax(avg_rating))
print("Lowest Rated movie:", np.argmin(avg_rating))
print("Movies not watched:", np.where(ratings == 0)[0])

for i in range(len(ratings)):
         unseen = np.where(ratings[i] == 0)[0]
         print(f"User {i+1} has not watched {unseen}")

user1_unseen = np.where(ratings[1] == 0)[0]
recommended = user1_unseen[np.argmax(avg_rating[user1_unseen])]
print("The recommended movie is:",recommended)

activity = np.count_nonzero(ratings, axis=1)
print("Most active user:", np.argmax(activity))

most_viewed = np.count_nonzero(ratings, axis=0)
print("The Most Times Rated is:", np.argmax(most_viewed))

user_avg_rating = np.mean(ratings,axis=1)
print(user_avg_rating,"User with highest average rating is:", np.argmax(user_avg_rating))

popularity = avg_rating * most_viewed
print(popularity,"Most popular movie is :", np.argmax(popularity))

Average Rating per movie: [2.75 1.25 0.   2.75]
Highest Rated movie: 0
Lowest Rated movie: 2
Movies not watched: [0 1 1 2 3 3]
User 1 has not watched [2]
User 2 has not watched [1 2]
User 3 has not watched [2]
User 4 has not watched [1 2]
The recommended movie is: 1
Most active user: 0
The Most Times Rated is: 0
[2.5  1.25 1.75 1.25] User with highest average rating is: 0
[11.   2.5  0.  11. ] Most popular movie is : 0


Project-5 : Image Analaysis

In [6]:
image = np.random.randint(0,255,(3,3))
print(image)

[[ 37 165 138]
 [ 93  87  56]
 [118  60 131]]


In [7]:
print(image)
print("Normalizing :", image / 255)
print("Increase Brightness:", image + 50)
print("Decrease Brightness:", image - 10)


[[ 37 165 138]
 [ 93  87  56]
 [118  60 131]]
Normalizing : [[0.14509804 0.64705882 0.54117647]
 [0.36470588 0.34117647 0.21960784]
 [0.4627451  0.23529412 0.51372549]]
Increase Brightness: [[ 87 215 188]
 [143 137 106]
 [168 110 181]]
Decrease Brightness: [[ 27 155 128]
 [ 83  77  46]
 [108  50 121]]
